name: Run Tests

on:
  push:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64
      - run: clang ./main.c -o output
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwrigth-report
          path: playwrigth-report
          retention-days: 5

      - name: Create Release
      - run: clang ./main.c -o output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
