name: Run Tests

on:
  push:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v2
  - uses: egor-tensin/setup-clang@v1
    with:
      version: latest
      platform: x64
  - run: clang ./main.c -o output
  - uses: actions/upload-artifact@v3
    if: always()
    with:
      name: playwrigth-report
      path: playwrigth-report
      retention-days: 5

